version = "3.8.6"

runner.dialect = scala3

maxColumn = 140
project.git = true
continuationIndent.defnSite = 2
align.preset = none
align.tokens = []
align.openParenCallSite = false
align.openParenDefnSite = false
assumeStandardLibraryStripMargin = true
danglingParentheses.preset = true
newlines.beforeCurlyLambdaParams = never
newlines.afterCurlyLambdaParams = never
newlines.topLevelStatementBlankLines = [{ blanks = 1 }]
newlines.penalizeSingleSelectMultiArgList = false

rewrite.rules = [
  AvoidInfix,
  Imports,
  PreferCurlyFors,
  RedundantParens,
  SortModifiers
]
rewrite.imports.sort = original
rewrite.redundantBraces.stringInterpolation = true

rewrite.neverInfix.excludeFilters = [
  "until",
  "to",
  "by",
  "eq",
  "ne",
  "should.*",
  "contain.*",
  "must.*",
  "in",
  "ignore",
  "be",
  "taggedAs",
  "thrownBy",
  "synchronized",
  "have",
  "when",
  "size",
  "only",
  "noneOf",
  "oneElementOf",
  "noElementsOf",
  "atLeastOneElementOf",
  "atMostOneElementOf",
  "allElementsOf",
  "inOrderElementsOf",
  "theSameElementsAs",
  "equal",
  "theSameElementsInOrderAs"
]
